### ISSUE TITLE
Can not generate the code, When the app haven't testFramework 

### ISSUE THREAD

**Issue by zhanyigo** [cbornet/generator-jhipster-grpc#18]
I generate my app which didn't choice a test framework.
Then generator-jhipster-grpc throws error every time. 
```
TypeError: Cannot read property 'includes' of undefined
    at child.displayLogo (/Users/zhanyi/node_modules/generator-jhipster-grpc/generators/app/index.js:35:44)
    at Object.<anonymous> (/Users/zhanyi/node_modules/yeoman-generator/lib/base.js:436:25)
    at /Users/zhanyi/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/zhanyi/node_modules/run-async/index.js:24:19
    at /Users/zhanyi/node_modules/yeoman-generator/lib/base.js:448:8
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

**Comment by cbornet** [comment]
I cherry-picked your first commit (contribution is credited to you). Thanks for the contribution !
